# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="DebianDefault"
DISC01 = "disks/"+HOSTNAME+"_sdb.vdi"

Vagrant.configure("2") do |config|
    # #Nome da Imagem que será baixada
    #config.vm.box = "debian/bookworm64"
    config.vm.box = "bento/debian-12"
    config.vm.box_check_update = false #Verificar o update da vbox
    config.vm.network "public_network", bridge: "default", type: "dhcp"
    config.vm.synced_folder "geral", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
     
      if File.exist?(DISC01)
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISC01]
      else
        vb.customize ['createhd', '--filename', DISC01, '--size', 10 * 1024]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISC01] 
      end
       
       vb.name = HOSTNAME 
       vb.cpus = 1 
       vb.gui = false 
       vb.memory = "1024" 
       vb.customize ["modifyvm", :id, "--groups", "/Lab02"]
    end
    #config.vm.provision "shell", inline: <<-SHELL SHELL
    config.vm.provision "shell", path:"scripts/"+HOSTNAME+".sh"
 end