# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="DebianDefault"
DISC01 = "disks/"+HOSTNAME+"_sdb.vdi"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.box_check_update = false 
    config.vm.network "public_network", bridge: "default", type: "dhcp"
    config.vm.synced_folder "geral", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| 
     
      if File.exist?(DISC01)
          vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISC01]
      else
        vb.customize ['createhd', '--filename', DISC01, '--size', 10 * 1024]
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISC01] 
      end
       
       vb.name = HOSTNAME 
       vb.cpus = 1 
       vb.gui = false 
       vb.memory = "1024" 
       vb.customize ["modifyvm", :id, "--groups", "/LPIC3-305"]
    end
    config.vm.provision "shell", inline: <<-SHELL 
      apt update -y
      apt install net-tools vim xfsprogs -y
      mkfs.xfs /dev/sdb
      mkdir /mnt/sdb -p
      mount /dev/sdb /mnt/sdb
      echo "/dev/sdb /mnt/sdb xfs defaults 0 0" >> /etc/fstab
      systemctl daemon-reload
      mount -a
    SHELL
 end