# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="Cloud-init"

Vagrant.configure("2") do |config|
    #config.vm.box = "debian/bookworm64"
    config.vm.box = "bento/debian-12"
    config.vm.box_check_update = false 

    config.vm.network "public_network", bridge: "default", type: "dhcp"
    #config.vm.synced_folder ".", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| 
       vb.name = HOSTNAME 
       vb.cpus = 2 
       vb.gui = false 
       vb.memory = "4024" 
       vb.customize ["modifyvm", :id, "--groups", "/LPIC3"]
    end
    config.vm.provision "shell", inline: <<-SHELL 
       sudo apt update -y
    SHELL
 end