# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="Docker"

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12"
    config.vm.box_check_update = true 

   # config.vm.network "public_network", bridge: "default", type: "dhcp"
    #config.vm.synced_folder ".", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| 
       vb.name = HOSTNAME 
       vb.cpus = 2 
       vb.gui = false 
       vb.memory = "4024" 
       vb.customize ["modifyvm", :id, "--groups", "/Containers"]
    end
   #  if File.exist?("docker-sdb")
   #    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISK]
   # else
   #    vb.customize ['createhd', '--filename', DISK, '--size', 20 * 1024]
   #    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISK] 
   # end
    config.vm.disk :disk, size:"10GB", name: "docker-sdb"

    config.vm.provision "shell", inline: <<-SHELL 
       apt update -y
       rcvboxadd quicksetup all
       hostnamectl set-hostname Docker
       poweroff
    SHELL
 end