# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   # #Nome da Imagem que será baixada
   config.vm.box = "debian/bookworm64"
   
   #config.vm.box_check_update = false #Verificar o update da vbox
   config.vm.network "private_network", ip: "192.168.33.11" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder ".", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/Lpic-305"]
	  #vb.customize ['createhd', '--filename', '/disk/sdb', '--size', 20 * 1024]
      #vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', '/disk/sdb.vdi']
            
      vb.name = "Db12Docker" #Definindo o nome da Máquina
      vb.cpus = 2 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "2048" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     hostnamectl set-hostname DockerDebian
     apt-get update -y
   SHELL
   # config.vm.provision "shell", path:"files/makedb.sh"
end
