# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   # #Nome da Imagem que será baixada
   config.vm.box = "debian/bookworm64"
   
   #config.vm.box_check_update = false #Verificar o update da vbox
   config.vm.network "public_network", bridge: "Killer E2600 Gigabit Ethernet Controller", type: "dhcp" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder "Files", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/Lpic-305"]
	         
      vb.name = "Db12-Xen" #Definindo o nome da Máquina
      vb.cpus = 2 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "4024" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     hostnamectl set-hostname DebianXen
     apt-get update -y
     apt install xen-system-amd64 xen-tools bridge-utils net-tools xfsprogs vim -y #Instalando as ferramentas do Xen
	 echo 'GRUB_CMDLINE_XEN_DEFAULT="dom0_max_vcpus=1 dom0_mem=1014M,max:1024M"' >> /etc/default/grub
    update-grub2 #Definindo Xen como boot no grub (atualizacao)
	 reboot
   SHELL
end

##Comandos para testar 
#xl info
#xl demesg | less
#xl list -> listará as vms

#Limitar uso de recursos da VM0
############## vi /etc/default/grub
#GRUB_CMDLINE_XEN_DEFAULT="dom0_max_vcpus=1 dom0_mem=1014M,max:1024M" Limitando cpu e memória (rodar  grub-mkconfig)