# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="db12xen"
DISC01 = "disks/"+HOSTNAME+"_sdb.vdi"
MEM="2048"
CPUS="2"
GRUPO="/Lab02_XEN"
BOX= "bento/debian-12"
 #config.vm.box = "debian/bookworm64" "bento/debian-12"

Vagrant.configure("2") do |config|
    # #Nome da Imagem que será baixada
   
    config.vm.box = BOX
    config.vm.box_check_update = true #Verificar o update da vbox
    #config.vm.network "public_network", bridge: "default", type: "dhcp"
    config.vm.network "public_network", type: "dhcp"
    config.vm.synced_folder "../Arquivos", "/vagrant" 
    config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
    if File.exist?(DISC01)
       vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISC01]
    else
       vb.customize ['createhd', '--filename', DISC01, '--size', 10 * 1024]
       vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISC01] 
     end
       
       vb.name = HOSTNAME 
       vb.cpus = CPUS
       vb.memory = MEM 
       vb.gui = false 
       vb.customize ["modifyvm", :id, "--groups", GRUPO]
    end
    config.vm.provision "shell", inline: <<-SHELL
        #Execução de script básico
        apt update -y
        apt install vim net-tools -y
        cp /vagrant/InstallXenComamnds /opt
    SHELL
    #config.vm.provision "shell", path:"scripts/"+HOSTNAME+".sh"
 end