# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="12Qemu"
CPU="6"
MEM="6098"
GUI=true
GROUP="/LPIC3V"
DISK="hdd/xens12db.vdi"
BRIDGE="Killer E2600 Gigabit Ethernet Controller"
IP="192.168.1.10"
Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    #config.vm.box = "bento/debian-12"
    config.vm.box_check_update = false 
    config.vm.network "public_network", bridge: BRIDGE, ip: "192.168.18.130", dns: "8.8.8.8"
   # config.vm.network "private_network", ip: IP
    config.vm.synced_folder ".", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| 
       vb.name = HOSTNAME 
       vb.cpus = CPU 
       vb.gui = GUI 
       vb.memory = MEM 
       vb.customize ["modifyvm", :id, "--groups", GROUP]
       if File.exist?(DISK)
         vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISK]
      else
         vb.customize ['createhd', '--filename', DISK, '--size', 20 * 1024]
         vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', DISK] 
      end
     end
   config.vm.provision "shell", inline: <<-SHELL 
       apt update -y
       #apt install xen-system-amd64 xen-tools vim zstd -y
    SHELL
 end